// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2yXtEv1M0zT6M-xy-Jt0oUptFu1UVaGQ',
    appId: '1:321733588663:web:90c99a39f57b109de2bf32',
    messagingSenderId: '321733588663',
    projectId: 'ecommerce-68a53',
    authDomain: 'ecommerce-68a53.firebaseapp.com',
    storageBucket: 'ecommerce-68a53.firebasestorage.app',
    measurementId: 'G-8V5RMPVQVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoNwUUO5Tz14IlFKd_HoaxvWHkrvHYYmo',
    appId: '1:321733588663:android:ff0fd265bd81a036e2bf32',
    messagingSenderId: '321733588663',
    projectId: 'ecommerce-68a53',
    storageBucket: 'ecommerce-68a53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDpHTXxsyZRxjbDBWbN2XX2pF5hnvwBhI',
    appId: '1:321733588663:ios:11a49dfaa9eda968e2bf32',
    messagingSenderId: '321733588663',
    projectId: 'ecommerce-68a53',
    storageBucket: 'ecommerce-68a53.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );
}
